"""simplify_tenant_model

Revision ID: 124a7e92fc2b
Revises: f387869b949d
Create Date: 2026-01-08 08:12:35.094880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '124a7e92fc2b'
down_revision: Union[str, Sequence[str], None] = 'f387869b949d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('suspension_reason', sa.Text(), nullable=True))
    op.add_column('tenants', sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tenants', sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('idx_type_status'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_legal_name'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_type'), table_name='tenants')
    op.create_index('idx_tenant_status_deleted', 'tenants', ['status', 'deleted_at'], unique=False)
    op.drop_column('tenants', 'legal_name')
    op.drop_column('tenants', 'team_size')
    op.drop_column('tenants', 'logo_url')
    op.drop_column('tenants', 'features')
    op.drop_column('tenants', 'email')
    op.drop_column('tenants', 'website')
    op.drop_column('tenants', 'type')
    op.drop_column('tenants', 'settings')
    op.drop_column('tenants', 'clerk_metadata')
    op.drop_column('tenants', 'tax_id')
    op.drop_column('tenants', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('tax_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('clerk_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('website', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('logo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('team_size', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('legal_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index('idx_tenant_status_deleted', table_name='tenants')
    op.create_index(op.f('ix_tenants_type'), 'tenants', ['type'], unique=False)
    op.create_index(op.f('ix_tenants_legal_name'), 'tenants', ['legal_name'], unique=False)
    op.create_index(op.f('idx_type_status'), 'tenants', ['type', 'status'], unique=False)
    op.drop_column('tenants', 'deactivated_at')
    op.drop_column('tenants', 'suspended_at')
    op.drop_column('tenants', 'suspension_reason')
    # ### end Alembic commands ###
