"""update_tenant_model_remove_clerk_brand_description

Revision ID: 13835dab6b8e
Revises: b3a9e0ec83e1
Create Date: 2026-01-06 14:29:33.926151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13835dab6b8e'
down_revision: Union[str, Sequence[str], None] = 'b3a9e0ec83e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SKIP: conversations and messages tables (manually created)
    # op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    # op.drop_index(op.f('ix_conversations_tenant_id'), table_name='conversations')
    # op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    # op.drop_table('conversations')
    # op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    # op.drop_index(op.f('ix_messages_id'), table_name='messages')
    # op.drop_table('messages')
    
    # Add new tenant columns
    op.add_column('tenants', sa.Column('legal_name', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('tax_id', sa.String(length=50), nullable=True))
    op.add_column('tenants', sa.Column('type', sa.String(length=50), nullable=True))
    op.add_column('tenants', sa.Column('team_size', sa.BigInteger(), nullable=True))
    
    # Remove old indexes
    op.drop_index(op.f('idx_brand_status'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_brand'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_clerk_org_id'), table_name='tenants')
    
    # Create new indexes
    op.create_index('idx_type_status', 'tenants', ['type', 'status'], unique=False)
    op.create_index(op.f('ix_tenants_legal_name'), 'tenants', ['legal_name'], unique=False)
    op.create_index(op.f('ix_tenants_type'), 'tenants', ['type'], unique=False)
    
    # Remove old columns
    op.drop_column('tenants', 'clerk_org_id')
    op.drop_column('tenants', 'brand')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Restore old columns
    op.add_column('tenants', sa.Column('brand', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('clerk_org_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    
    # Remove new indexes
    op.drop_index(op.f('ix_tenants_type'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_legal_name'), table_name='tenants')
    op.drop_index('idx_type_status', table_name='tenants')
    
    # Restore old indexes
    op.create_index(op.f('ix_tenants_clerk_org_id'), 'tenants', ['clerk_org_id'], unique=True)
    op.create_index(op.f('ix_tenants_brand'), 'tenants', ['brand'], unique=False)
    op.create_index(op.f('idx_brand_status'), 'tenants', ['brand', 'status'], unique=False)
    
    # Remove new columns
    op.drop_column('tenants', 'team_size')
    op.drop_column('tenants', 'type')
    op.drop_column('tenants', 'tax_id')
    op.drop_column('tenants', 'legal_name')
    
    # SKIP: conversations and messages tables (manually created)
    # op.create_table('messages', ...)
    # op.create_index(...)
    # op.create_table('conversations', ...)
    # ### end Alembic commands ###

