"""convert_membership_role_to_string

Revision ID: 1c411a16edc9
Revises: 2ba2435e987c
Create Date: 2026-01-05 04:17:49.443816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c411a16edc9'
down_revision: Union[str, Sequence[str], None] = '2ba2435e987c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('memberships', 'role',
               existing_type=postgresql.ENUM('owner', 'admin', 'member', 'viewer', name='membershiprole'),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('memberships', 'role',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('owner', 'admin', 'member', 'viewer', name='membershiprole'),
               existing_nullable=False)
    # ### end Alembic commands ###
