"""convert_tenant_status_to_string

Revision ID: 2ba2435e987c
Revises: c077dc7102a1
Create Date: 2026-01-05 04:14:32.453463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ba2435e987c'
down_revision: Union[str, Sequence[str], None] = 'c077dc7102a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'status',
               existing_type=postgresql.ENUM('active', 'inactive', 'suspended', 'trial', name='tenantstatus'),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('active', 'inactive', 'suspended', 'trial', name='tenantstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###
