"""add_otp_fields_to_users

Revision ID: 3638242c1b8f
Revises: 1981171f4858
Create Date: 2025-12-12 08:26:22.996688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3638242c1b8f'
down_revision: Union[str, Sequence[str], None] = '1981171f4858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_otp', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_otp_expiry', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_otp_expiry')
    op.drop_column('users', 'reset_otp')
    # ### end Alembic commands ###
