"""make_business_fields_nullable

Revision ID: 56272174f5c1
Revises: aa9c09f95d55
Create Date: 2026-01-05 03:48:57.678508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56272174f5c1'
down_revision: Union[str, Sequence[str], None] = 'aa9c09f95d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_billing_credits_billing_profile_id'), 'billing_credits', ['billing_profile_id'], unique=False)
    op.create_index(op.f('ix_billing_credits_id'), 'billing_credits', ['id'], unique=False)
    op.create_index(op.f('ix_billing_credits_tenant_id'), 'billing_credits', ['tenant_id'], unique=False)
    op.alter_column('billing_profiles', 'provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_index(op.f('ix_billing_profiles_created_at'), 'billing_profiles', ['created_at'], unique=False)
    op.create_index(op.f('ix_billing_profiles_id'), 'billing_profiles', ['id'], unique=False)
    op.create_unique_constraint(None, 'billing_profiles', ['stripe_customer_id'])
    op.alter_column('businesses', 'legal_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('businesses', 'type',
               existing_type=postgresql.ENUM('llc', 'corporation', 'partnership', 'sole_proprietorship', 'nonprofit', 'other', name='businesstype'),
               nullable=True)
    op.alter_column('businesses', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('businesses', 'phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('businesses', 'address',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.create_index('idx_tenant_type', 'businesses', ['tenant_id', 'type'], unique=False)
    op.create_index(op.f('ix_businesses_email'), 'businesses', ['email'], unique=False)
    op.create_index(op.f('ix_businesses_name'), 'businesses', ['name'], unique=False)
    op.create_index(op.f('ix_businesses_owner_user_id'), 'businesses', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_businesses_status'), 'businesses', ['status'], unique=False)
    op.create_index(op.f('ix_businesses_type'), 'businesses', ['type'], unique=False)
    op.alter_column('invoice_line_items', 'quantity',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_index(op.f('ix_invoice_line_items_id'), 'invoice_line_items', ['id'], unique=False)
    op.create_index(op.f('ix_invoice_line_items_invoice_id'), 'invoice_line_items', ['invoice_id'], unique=False)
    op.alter_column('invoices', 'subtotal_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('invoices', 'tax_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('invoices', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.create_index(op.f('ix_invoices_billing_profile_id'), 'invoices', ['billing_profile_id'], unique=False)
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_index(op.f('ix_invoices_subscription_id'), 'invoices', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_invoices_tenant_id'), 'invoices', ['tenant_id'], unique=False)
    op.create_unique_constraint(None, 'invoices', ['provider_invoice_id'])
    op.alter_column('memberships', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index(op.f('ix_memberships_id'), 'memberships', ['id'], unique=False)
    op.create_index(op.f('ix_memberships_is_active'), 'memberships', ['is_active'], unique=False)
    op.create_index(op.f('ix_memberships_role'), 'memberships', ['role'], unique=False)
    op.create_index('ix_memberships_user_tenant_active', 'memberships', ['user_id', 'tenant_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_payments_billing_profile_id'), 'payments', ['billing_profile_id'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_tenant_id'), 'payments', ['tenant_id'], unique=False)
    op.create_unique_constraint(None, 'payments', ['provider_payment_id'])
    op.drop_index(op.f('ix_permissions_active'), table_name='permissions')
    op.create_index('idx_permission_active', 'permissions', ['is_active'], unique=False)
    op.alter_column('products', 'version',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_index('idx_product_active_current', 'products', ['is_active', 'is_current'], unique=False)
    op.create_index('idx_product_code_version', 'products', ['code', 'version'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_is_active'), 'products', ['is_active'], unique=False)
    op.create_index(op.f('ix_products_is_current'), 'products', ['is_current'], unique=False)
    op.create_index(op.f('ix_products_is_public'), 'products', ['is_public'], unique=False)
    op.create_unique_constraint(None, 'products', ['stripe_product_id'])
    op.create_index(op.f('ix_subscriptions_billing_profile_id'), 'subscriptions', ['billing_profile_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_product_id'), 'subscriptions', ['product_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_tenant_id'), 'subscriptions', ['tenant_id'], unique=False)
    op.create_unique_constraint(None, 'subscriptions', ['stripe_subscription_id'])
    op.create_index(op.f('ix_tenants_brand'), 'tenants', ['brand'], unique=False)
    op.create_index(op.f('ix_tenants_name'), 'tenants', ['name'], unique=False)
    op.create_index(op.f('ix_tenants_status'), 'tenants', ['status'], unique=False)
    op.alter_column('usage_records', 'quantity',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_index(op.f('ix_usage_records_id'), 'usage_records', ['id'], unique=False)
    op.create_index(op.f('ix_usage_records_metric'), 'usage_records', ['metric'], unique=False)
    op.create_index(op.f('ix_usage_records_subscription_id'), 'usage_records', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_usage_records_tenant_id'), 'usage_records', ['tenant_id'], unique=False)
    op.create_index('idx_brand_source', 'users', ['brand', 'lead_source'], unique=False)
    op.create_index(op.f('ix_users_brand'), 'users', ['brand'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_lead_source'), 'users', ['lead_source'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_lead_source'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_brand'), table_name='users')
    op.drop_index('idx_brand_source', table_name='users')
    op.drop_index(op.f('ix_usage_records_tenant_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_subscription_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_metric'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_id'), table_name='usage_records')
    op.alter_column('usage_records', 'quantity',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_index(op.f('ix_tenants_status'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_brand'), table_name='tenants')
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.drop_index(op.f('ix_subscriptions_tenant_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_product_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_billing_profile_id'), table_name='subscriptions')
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_index(op.f('ix_products_is_public'), table_name='products')
    op.drop_index(op.f('ix_products_is_current'), table_name='products')
    op.drop_index(op.f('ix_products_is_active'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index('idx_product_code_version', table_name='products')
    op.drop_index('idx_product_active_current', table_name='products')
    op.alter_column('products', 'version',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_index('idx_permission_active', table_name='permissions')
    op.create_index(op.f('ix_permissions_active'), 'permissions', ['is_active'], unique=False)
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_index(op.f('ix_payments_tenant_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_billing_profile_id'), table_name='payments')
    op.drop_index('ix_memberships_user_tenant_active', table_name='memberships')
    op.drop_index(op.f('ix_memberships_role'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_is_active'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_id'), table_name='memberships')
    op.alter_column('memberships', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(None, 'invoices', type_='unique')
    op.drop_index(op.f('ix_invoices_tenant_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_subscription_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_billing_profile_id'), table_name='invoices')
    op.alter_column('invoices', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('invoices', 'tax_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('invoices', 'subtotal_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.drop_index(op.f('ix_invoice_line_items_invoice_id'), table_name='invoice_line_items')
    op.drop_index(op.f('ix_invoice_line_items_id'), table_name='invoice_line_items')
    op.alter_column('invoice_line_items', 'quantity',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_index(op.f('ix_businesses_type'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_status'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_owner_user_id'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_name'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_email'), table_name='businesses')
    op.drop_index('idx_tenant_type', table_name='businesses')
    op.alter_column('businesses', 'address',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('businesses', 'phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('businesses', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('businesses', 'type',
               existing_type=postgresql.ENUM('llc', 'corporation', 'partnership', 'sole_proprietorship', 'nonprofit', 'other', name='businesstype'),
               nullable=False)
    op.alter_column('businesses', 'legal_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'billing_profiles', type_='unique')
    op.drop_index(op.f('ix_billing_profiles_id'), table_name='billing_profiles')
    op.drop_index(op.f('ix_billing_profiles_created_at'), table_name='billing_profiles')
    op.alter_column('billing_profiles', 'provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('ix_billing_credits_tenant_id'), table_name='billing_credits')
    op.drop_index(op.f('ix_billing_credits_id'), table_name='billing_credits')
    op.drop_index(op.f('ix_billing_credits_billing_profile_id'), table_name='billing_credits')
    # ### end Alembic commands ###
