"""add_newsletter_to_leads

Revision ID: 6cdaa191e5ca
Revises: d8ee4d7336f5
Create Date: 2025-12-08 09:52:49.086809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cdaa191e5ca'
down_revision: Union[str, Sequence[str], None] = 'd8ee4d7336f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('newsletter', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'newsletter')
    # ### end Alembic commands ###
