"""add_product_tenant_business_type_and_invoice_product_link

Revision ID: b3a9e0ec83e1
Revises: 04dd353d03eb
Create Date: 2026-01-06 03:52:30.084099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3a9e0ec83e1'
down_revision: Union[str, Sequence[str], None] = '04dd353d03eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add product_id to invoice_line_items
    op.add_column('invoice_line_items', sa.Column('product_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_invoice_line_items_product_id'), 'invoice_line_items', ['product_id'], unique=False)
    op.create_foreign_key(None, 'invoice_line_items', 'products', ['product_id'], ['id'])
    op.drop_column('invoice_line_items', 'description')
    
    # Add new fields to products
    op.add_column('products', sa.Column('tenant_id', sa.BigInteger(), nullable=False))
    op.add_column('products', sa.Column('business_id', sa.BigInteger(), nullable=True))
    op.add_column('products', sa.Column('created_by', sa.BigInteger(), nullable=False))
    op.add_column('products', sa.Column('type', sa.String(length=50), nullable=False))
    op.add_column('products', sa.Column('price_fixed', sa.Numeric(precision=10, scale=2), nullable=True))
    op.create_index(op.f('ix_products_business_id'), 'products', ['business_id'], unique=False)
    op.create_index(op.f('ix_products_created_by'), 'products', ['created_by'], unique=False)
    op.create_index(op.f('ix_products_tenant_id'), 'products', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_products_type'), 'products', ['type'], unique=False)
    op.create_foreign_key(None, 'products', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'products', 'businesses', ['business_id'], ['id'])
    op.create_foreign_key(None, 'products', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert products changes
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_type'), table_name='products')
    op.drop_index(op.f('ix_products_tenant_id'), table_name='products')
    op.drop_index(op.f('ix_products_created_by'), table_name='products')
    op.drop_index(op.f('ix_products_business_id'), table_name='products')
    op.drop_column('products', 'price_fixed')
    op.drop_column('products', 'type')
    op.drop_column('products', 'created_by')
    op.drop_column('products', 'business_id')
    op.drop_column('products', 'tenant_id')
    
    # Revert invoice_line_items changes
    op.add_column('invoice_line_items', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'invoice_line_items', type_='foreignkey')
    op.drop_index(op.f('ix_invoice_line_items_product_id'), table_name='invoice_line_items')
    op.drop_column('invoice_line_items', 'product_id')
    # ### end Alembic commands ###
