"""add_user_history_remove_session_tenant_soft_delete

Revision ID: bae947ba425b
Revises: e0f718e39b50
Create Date: 2025-12-30 08:13:42.908206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bae947ba425b'
down_revision: Union[str, Sequence[str], None] = 'e0f718e39b50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('action_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_action_created', 'user_history', ['action', 'created_at'], unique=False)
    op.create_index('idx_entity', 'user_history', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_user_action', 'user_history', ['user_id', 'action'], unique=False)
    op.create_index('idx_user_created', 'user_history', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_user_history_action'), 'user_history', ['action'], unique=False)
    op.create_index(op.f('ix_user_history_clerk_user_id'), 'user_history', ['clerk_user_id'], unique=False)
    op.create_index(op.f('ix_user_history_created_at'), 'user_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_history_entity_type'), 'user_history', ['entity_type'], unique=False)
    op.create_index(op.f('ix_user_history_id'), 'user_history', ['id'], unique=False)
    op.create_index(op.f('ix_user_history_user_id'), 'user_history', ['user_id'], unique=False)
    op.drop_index(op.f('idx_tenant_status'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_tenant_id'), table_name='sessions')
    op.drop_column('sessions', 'tenant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('tenant_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_sessions_tenant_id'), 'sessions', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_tenant_status'), 'sessions', ['tenant_id', 'status'], unique=False)
    op.drop_index(op.f('ix_user_history_user_id'), table_name='user_history')
    op.drop_index(op.f('ix_user_history_id'), table_name='user_history')
    op.drop_index(op.f('ix_user_history_entity_type'), table_name='user_history')
    op.drop_index(op.f('ix_user_history_created_at'), table_name='user_history')
    op.drop_index(op.f('ix_user_history_clerk_user_id'), table_name='user_history')
    op.drop_index(op.f('ix_user_history_action'), table_name='user_history')
    op.drop_index('idx_user_created', table_name='user_history')
    op.drop_index('idx_user_action', table_name='user_history')
    op.drop_index('idx_entity', table_name='user_history')
    op.drop_index('idx_action_created', table_name='user_history')
    op.drop_table('user_history')
    # ### end Alembic commands ###
