"""convert_business_enums_to_string

Revision ID: c077dc7102a1
Revises: 56272174f5c1
Create Date: 2026-01-05 04:09:52.339064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c077dc7102a1'
down_revision: Union[str, Sequence[str], None] = '56272174f5c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('businesses', 'type',
               existing_type=postgresql.ENUM('llc', 'corporation', 'partnership', 'sole_proprietorship', 'nonprofit', 'other', name='businesstype'),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('businesses', 'status',
               existing_type=postgresql.ENUM('active', 'inactive', 'pending', 'suspended', name='businessstatus'),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('businesses', 'status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('active', 'inactive', 'pending', 'suspended', name='businessstatus'),
               existing_nullable=False)
    op.alter_column('businesses', 'type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('llc', 'corporation', 'partnership', 'sole_proprietorship', 'nonprofit', 'other', name='businesstype'),
               existing_nullable=True)
    # ### end Alembic commands ###
