"""add_is_primary_to_membership

Revision ID: d2d60301423a
Revises: 1c411a16edc9
Create Date: 2026-01-05 06:33:32.991621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2d60301423a'
down_revision: Union[str, Sequence[str], None] = '1c411a16edc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('memberships', sa.Column('is_primary', sa.Boolean(), nullable=True))
    
    # Set default value for existing records (first membership per user is primary)
    op.execute("""
        UPDATE memberships m1
        SET is_primary = TRUE
        WHERE id = (
            SELECT MIN(id)
            FROM memberships m2
            WHERE m2.user_id = m1.user_id
        )
    """)
    
    # Set remaining records to FALSE
    op.execute("UPDATE memberships SET is_primary = FALSE WHERE is_primary IS NULL")
    
    # Now make it NOT NULL
    op.alter_column('memberships', 'is_primary', nullable=False)
    
    op.create_index(op.f('ix_memberships_is_primary'), 'memberships', ['is_primary'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memberships_is_primary'), table_name='memberships')
    op.drop_column('memberships', 'is_primary')
    # ### end Alembic commands ###
