"""add_newsletter_to_users

Revision ID: e3951472ac8e
Revises: 6cdaa191e5ca
Create Date: 2025-12-08 09:57:47.613973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3951472ac8e'
down_revision: Union[str, Sequence[str], None] = '6cdaa191e5ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('newsletter', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'newsletter')
    # ### end Alembic commands ###
