"""v2-model name change

Revision ID: e653d8acd75c
Revises: 23056ee23881
Create Date: 2025-12-30 05:32:59.328090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e653d8acd75c'
down_revision: Union[str, Sequence[str], None] = '23056ee23881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_memberships_id'), table_name='memberships')
    op.drop_index(op.f('ix_tenant_memberships_is_active'), table_name='memberships')
    op.drop_index(op.f('ix_tenant_memberships_role'), table_name='memberships')
    op.drop_index(op.f('ix_tenant_memberships_tenant_id'), table_name='memberships')
    op.drop_index(op.f('ix_tenant_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_tenant_memberships_user_tenant_active'), table_name='memberships')
    op.create_index(op.f('ix_memberships_id'), 'memberships', ['id'], unique=False)
    op.create_index('ix_memberships_is_active', 'memberships', ['is_active'], unique=False)
    op.create_index('ix_memberships_role', 'memberships', ['role'], unique=False)
    op.create_index('ix_memberships_tenant_id', 'memberships', ['tenant_id'], unique=False)
    op.create_index('ix_memberships_user_id', 'memberships', ['user_id'], unique=False)
    op.create_index('ix_memberships_user_tenant_active', 'memberships', ['user_id', 'tenant_id', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_memberships_user_tenant_active', table_name='memberships')
    op.drop_index('ix_memberships_user_id', table_name='memberships')
    op.drop_index('ix_memberships_tenant_id', table_name='memberships')
    op.drop_index('ix_memberships_role', table_name='memberships')
    op.drop_index('ix_memberships_is_active', table_name='memberships')
    op.drop_index(op.f('ix_memberships_id'), table_name='memberships')
    op.create_index(op.f('ix_tenant_memberships_user_tenant_active'), 'memberships', ['user_id', 'tenant_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_tenant_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_index(op.f('ix_tenant_memberships_tenant_id'), 'memberships', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tenant_memberships_role'), 'memberships', ['role'], unique=False)
    op.create_index(op.f('ix_tenant_memberships_is_active'), 'memberships', ['is_active'], unique=False)
    op.create_index(op.f('ix_tenant_memberships_id'), 'memberships', ['id'], unique=False)
    # ### end Alembic commands ###
