"""Add leads table and remove user verification fields

Revision ID: fb77ba01b1d5
Revises: 75a16f33b7f5
Create Date: 2025-12-08 03:25:26.739764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb77ba01b1d5'
down_revision: Union[str, Sequence[str], None] = '75a16f33b7f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'token_expiry')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token_expiry', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('verification_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
